list = [
	"「晒宁」说: 0110 0001 0110 0000 1011 0001 1111 1000",
	"「卷儿」说: 萌萌的我要走啦, 不要想念我, 开启你星辰大海的征途吧ε==(づ′▽`)づ",
	"「天选」说: 距离飞船爆炸还有30秒, 我就先走啦",
	"「抹香」说: 虽然我很想跟你一起飞下去, 但是卷卷老婆叫我回家吃饭了, 所以拜拜啦(*￣3￣)╭",
	"「抹香」还说: 我只跟我老婆飞, 不要以为你邀请我, 我就会跟你走, 我叶良辰不是这样的人.",
	"「那啥」说: 本公举不是轻易帮飞的, 帮你飞了记得回报我洗白白去吧, 我先去床上等你了(￣^￣)ゞ",
	"「那啥」还说: 一路顺风欢迎下次使用; 豆浆牌帮飞, 就是香; 天选那个棒; 容我思考一下.",
	"「那啥」正经说: あなたのことが好きだけどもうあきらめます じゃさよなら",
]