list = [
	"「晒宁」说: 哎, 一大清早脑回路就堵车, 我还是应该回去喝三个核桃补补大脑, 不用管我了, 拜了个拜!",
	"「卷儿」说: 萌萌的我要走啦, 不要想念我, 开启你星辰大海的征途吧ε==(づ′▽`)づ",
	"「天选」说: 距离飞船爆炸还有30秒, 我就先走啦",
	"「抹香」说: 虽然我很想跟你一起飞下去, 但是卷卷老婆叫我回家吃饭了, 所以拜拜啦(*￣3￣)╭",
	"「那啥」说: 本公举不是轻易帮飞的, 帮你飞了记得回报我洗白白去吧, 我先去床上等你了(￣^￣)ゞ",
	"「肥兔纸」说: _ . . .  _ . _ _  .",
	"「大空」说: Have a good time～୧(๑•̀⌄•́๑)૭",
	"「桃乐丝」说: 啊朋友再见, 啊朋友再见吧再见吧再见吧~",
	"「大河」说: 海阔天空任你浪, 良辰不奉陪了ε=ε=ε=ε=ε=ε=┌(;￣◇￣)┘",
	"「七大喵」说: 虽然我貌美如花, 人见人爱, 花见花开. 可是我就如春风一样无法被抓住…so~白白了, 放手!再见!",
	"「会长」说: 任务已完成, AI5102号关闭.",
	"「花仙子小太阳」说: 美丽的警察姐姐温馨提示: 右侧通行 限速30 (*´ｪ`*)",
	"「Saber」说: 祝您旅途愉快，单飞顺利括弧笑:)",
	"「耗子和树蛙」说: 哎咦！我们都不会飞！吱～呱～ᶘ ᵒᴥᵒᶅ",
	"「白树」说: Namárië! Nai hiruvalyë Valimar. Nai elyë hiruva. 愿伊鲁维塔与你同在(´-灬-‘)",
	"「尾巴」说: 虫丶尾巴 现已加入豆浆帮飞套餐，订餐电话就是不告诉你。",
]