list = [
	"「卷儿」说: 萌萌的我要走啦, 不要想念我, 开启你星辰大海的征途吧ε==(づ′▽`)づ",
	"「天选」说: 距离飞船爆炸还有30秒, 我就先走啦",
	"「抹香」还说: 我只跟我老婆飞, 不要以为你邀请我, 我就会跟你走, 我叶良辰不是这样的人.",
	"「肥兔纸」说: _ . . .  _ . _ _  .",
	"「七大喵」说: 虽然我貌美如花, 人见人爱, 花见花开. 可是我就如春风一样无法被抓住…so~白白了, 放手!再见!",
	"「会长」说: 任务已完成, AI5102号关闭.",
	"「花仙子小太阳」说: 美丽的警察姐姐温馨提示: 右侧通行 限速30 (*´ｪ`*)",
	"「树蛙」说: 耗子和树蛙说 哎咦！我们都不会飞！吱～呱～ᶘ ᵒᴥᵒᶅ",
]