[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:shAXbQ8KM4ut_QxKiqFL52gjzHUYTZZQB-8-qVecd5M"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTU2NjFkNWYyYjc5YmE2YzMzMTNmZDE0Nzc3N2NmNTdhBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--2142fdbdcc8ba67fa834f17a7ba37f0c47d0e3c3; __cfduid=df1005e9536db3906806c7407c7a25aef1446453236"
	IfNoneMatch = "b0505fcb96c461aa0062d790fab55655"
	ConvertedEnergy = 0

[[PlayerInfo]]
	Name = "豆喵子"
	AuthToken = "370945:fcAGgjjCzt2pFEBNonnzWnr65fGyNYvCg9SUHFncsDQ"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTVhZGE2MGMzNzUxY2M0NjAxMmM0YzZkMDJiMTQ0NjYzBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--71742b31f176efac8ec0110ed3c619fac87f66e9; __cfduid=d534cd265cc169f784f80d48af2bafdf21444184209"
	IfNoneMatch = "4ecbdbb0c9bfd061cfcbaccaa7a9bffa"
	ConvertedEnergy = 0

[[PlayerInfo]]
	Name = "宅家豆浆"
	AuthToken = "473033:C4n9KGgivumMhFNqR29psHFsEZRA7CxxUokosDZExR4"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTU5YTEwYjk4ZmVlOTc1MDA0ZjFiN2U2Y2YzOWNiNjQzBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--e3b0f65033b705e5097f81e595085b636e61f762; __cfduid=db6ae664c9929a7a2c1e400207b4e63c71443003916"
	IfNoneMatch = "0b88a736758073d10aca6ed18851ba15"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家白小猫"
	AuthToken = "477860:afL1_oamjPKvzjVEseBtASF7SwQhBKuEs-U41fyELHz"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWU4NzdjMGViZTM0YzEwZDkxMDA5ZjYxYmEyYWZhNzVhBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--45107041393731414997b02f6a158adf5cb13081; __cfduid=d0f1cef52baf17d4647b6a674a0f9df681444279622"
	IfNoneMatch = "be72b64d7690ddabc24445f689b07d18"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家飞碟"
	AuthToken = "543972:u1r8n_TzzmamsuC8AT142-T48sSWrJxo4RYPac-5VXY"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWM4MjZlY2Q3ZGM1NjcxOWNmZjZhZTAzNTJhY2UxNzVkBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--ec3366d69081bf6199571e572df8d9c3624e1a8b; __cfduid=d8a93a59248eee274519aa0cd1c90d7e21444280520"
	IfNoneMatch = "f158c0be4aa2dd39ccee5fb4fc7ecb9d"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家拉佛"
	AuthToken = "548754:DTXqwxKJshh_B9xjbXV3RFoxT5TA6rreK3-JBARkxiz"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWYwZGY2MDNlNmM5ZTdkMjA4OWQyNjk1NTVjZWFhYWU2BjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--6e63077e6d5dbdf80b2030440f3402ca800300c1; __cfduid=de0eabb3c2a3bd360ac4d168bb59a7f7a1444647143"
	IfNoneMatch = "f158c0be4aa2dd39ccee5fb4fc7ecb9d"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家琪萨"
	AuthToken = "549457:ACQ6b2sKxckyB1PmZdyoishsvVP7VZNoEqgDzuwMUP4"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTU4ODIxMGExZGExZWMzNDY3MGQwZDM0OTYyY2M4NDUwBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--919ef308fc20bb139f2ad107545bc768e00937f9; __cfduid=d5a8c09fb0e64413426b1b8fd6ad9e6621444711078"
	IfNoneMatch = "f158c0be4aa2dd39ccee5fb4fc7ecb9d"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家豆腐"
	AuthToken = "556918:syGGPx_zWMbAr4kiGrT6RJ-wye366TgH8h1hLFw4xdx"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWQ2MWM2YWQ3ZTQyN2NkMjlkNjIxYWI1NzEzNjRmYmRlBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--182e955907490fd69366f753231bb7876a404f1b; __cfduid=d385a1676f696030d3430f735eb9b54101445334119"
	IfNoneMatch = "f158c0be4aa2dd39ccee5fb4fc7ecb9d"
	ConvertedEnergy = 0
	
[[PlayerInfo]]
	Name = "宅家豆汁"
	AuthToken = "557451:FSzj-3dv4CTLzChySdrd12aV8TCd6AmFsBsebaJb3Gz"
	ClientVersion = "2.1.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWI5Y2Y5ZTQyOGM1NWIzYjA5ODVkY2M1MTlmZTMyYmJhBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--e430b23e01e49eed7ba8280b18e169a9e4a5470a; __cfduid=d9bedef3b5764bb7bca057d3fd8a106fd1446451594"
	IfNoneMatch = "eeffc0ec523790a4977aab85d39ad16e"
	ConvertedEnergy = 0