[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:L-1VDNuTARvi_1ucrW8TY-yxW2uWs-Ygec6XfnDqyzo"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWY2MzFmNDA4YjQ1NGYxODkzMTlkMDA4ZGMzYTEwMzBhBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--db305f92f95348ea230fbc823519e9ae3f9c3790; __cfduid=db33dbbc0495a6bf3d4c5aef7f50a7b391451270881"
	IfNoneMatch = "3137a7608cc8e68089cac133130eef8b"
	ConvertedEnergy = 0