[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:cRKLiJZhcU1uWVzNhHk_5jxs2PHVuz1crmz6xJ7jK1s"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTRmOTVmOWI3YjA1NjBjNmExZDg0ZDQ3ZDM5Mzc2YTMwBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--b7f3f3b606833fb6804fba134cf6ec11b282c079; __cfduid=d978958516b17a4c645154210bd58d5be1451552838"
	IfNoneMatch = "3137a7608cc8e68089cac133130eef8b"
	ConvertedEnergy = 0