[[PlayerInfo]]
	Name = "宅家豆浆"
	AuthToken = "473033:SST_rigzrx1dND5Pvg-xGxsrkbfyomRPMDzsSagbrqQ"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWJjYjRiNjhlZGYyMWQzMTdlZGNiOGQ5ZWE5ZDJjODZkBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--deaeb4fc961b1659fd6161a254f7dc33308f6991; __cfduid=db6ae664c9929a7a2c1e400207b4e63c71443003916"
	IfNoneMatch = "0b88a736758073d10aca6ed18851ba15"
	ConvertedEnergy = 0