[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:cuAqf4RbsJhgkVPvwHB8os2MDdFBy15tFST7BrkM6C8"
	ClientVersion = "2.1.5"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTI4ZDI1YTdjMmMxN2RhYWQ5MWI1YTY1YWRkYTAzYmI5BjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--dc32dbded54691404024ecc64e36497551940ae8"
	ConvertedEnergy = 0
	EpicHelper = true

[[PlayerInfo]]
	Name = "宅家豆浆"
	AuthToken = "473033:BHfwd8tMFV98KA5s_qGsP-kJBVrKe8EZTTgy1-3vV1c"
	ClientVersion = "2.1.5"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTA0ZGE5ZWMyNzhiNDU4NjZjOWFiNGI4NmY0MDQxNGE5BjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--82ad33ec1a8882aadfdc10fb0f71146edae8e607"
	ConvertedEnergy = 0
	EpicHelper = true
	
[[PlayerInfo]]
	Name = "宅家白小猫"
	AuthToken = "477860:e2iz5Ts3-sVwThW-cu9VLLUSwWqk3fi5i-1aCrSa3aE"
	ClientVersion = "2.1.5"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTZlZGUwOWU1MTBkMjI0ZjJmMWNiNjg5YzI0MTJlN2Y4BjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--8de5111e28004718450c7c199687643bb2720a71"
	ConvertedEnergy = 0
	EpicHelper = false
	
[[PlayerInfo]]
	Name = "宅家飞碟"
	AuthToken = "543972:_sn5uAg-19_4Wsx4du9N7XFjzSNL6yva4mPLksvxvvx"
	ClientVersion = "2.1.5"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTZmNTFhMWI5ZmIzZWQ4OWYwNDhhMjEzYmIyZmJiODI5BjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--4a2044c55aa1a01cffa3b7ff48a8970574da3a49"
	ConvertedEnergy = 0
	EpicHelper = false
	
[[PlayerInfo]]
	Name = "宅家拉佛"
	AuthToken = "548754:m-fAbVDYY26UKE8dbSecdy2j912Qomnxq2kyUn98uCs"
	ClientVersion = "2.1.5"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWQxOGYzZTRiOWJmMTgzODA0Zjg0MDNlMjAzZmRhODdiBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--b0bb1d453c948262bd7f583adabbe6e4c1c600e8"
	ConvertedEnergy = 0
	EpicHelper = false
	
[[PlayerInfo]]
	Name = "宅家琪萨"
	AuthToken = "549457:ACQ6b2sKxckyB1PmZdyoishsvVP7VZNoEqgDzuwMUP4"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTU4ODIxMGExZGExZWMzNDY3MGQwZDM0OTYyY2M4NDUwBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--919ef308fc20bb139f2ad107545bc768e00937f9; __cfduid=d5a8c09fb0e64413426b1b8fd6ad9e6621444711078"
	ConvertedEnergy = 0
	EpicHelper = false
	
[[PlayerInfo]]
	Name = "宅家豆汁"
	AuthToken = "557451:FSzj-3dv4CTLzChySdrd12aV8TCd6AmFsBsebaJb3Gz"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWI5Y2Y5ZTQyOGM1NWIzYjA5ODVkY2M1MTlmZTMyYmJhBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--e430b23e01e49eed7ba8280b18e169a9e4a5470a; __cfduid=d9bedef3b5764bb7bca057d3fd8a106fd1446451594"
	ConvertedEnergy = 0
	EpicHelper = false
	
[[PlayerInfo]]
	Name = "宅家豆腐脑"
	AuthToken = "595538:G_5fCx4jE3sZXjCSXbBcBsW_eDnAU6HffGe6BvJhnTw"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTYxMTdjNTdjNWYxYjU3M2VkYTgwMjBkMzAyOTliOGExBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--7d6dadef55f04b566d7edb20679e1375ddb27f9b; __cfduid=dda7bf0ce2b731360ff46d66db2e06f131448440750"
	ConvertedEnergy = 0
	EpicHelper = false

[[PlayerInfo]]
	Name = "宅家豆腐"
	AuthToken = "556918:syGGPx_zWMbAr4kiGrT6RJ-wye366TgH8h1hLFw4xdx"
	ClientVersion = "2.1.4"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWQ2MWM2YWQ3ZTQyN2NkMjlkNjIxYWI1NzEzNjRmYmRlBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFQ%3D--182e955907490fd69366f753231bb7876a404f1b; __cfduid=d385a1676f696030d3430f735eb9b54101445334119"
	ConvertedEnergy = 0
	EpicHelper = false