[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:z8Z2e1xBxKJPKQ1vcs9mMHHHunKEyTRCziRQqyiC_yk"
	ClientVersion = "3.0.13"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTZhNmI3MDgzNjEyOTlkODNmNmUyMTgyMWJiMGQ2MzlkBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--3a563e76e501b212e0bc17c519c4dd3e238a78e4"
	ConvertedEnergy = 0
	EpicHelper = false

[[PlayerInfo]]
	Name = "Twitter晒宁鼻涕"
	AuthToken = "633899:B721PRgsjRooms2zMKytZ2a4XdtsrQyo6SfLtoHbrdE"
	ClientVersion = "3.0.13"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_spacewalk-server_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTE5ZTEyNDg1NGRlOWI0MDIyZWRiMDE5YWM3ZjkwNjAzBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFQ%3D--90b61d2b8ae3b2c560b0a99d934728061b085deb"
	ConvertedEnergy = 0
	EpicHelper = false