[[PlayerInfo]]
	Name = "晒宁鼻涕"
	AuthToken = "370797:MgyAsT2_5RzoyLfvY5-KYLsEdTL6hTCakWPeNXz7NxY"
	ClientVersion = "4.8.4.3"
	Locale = "zh-CN"
	Platform = "ios"
	Cookie = "_mkra_ctxt=210cc965df86d83c843da4754785b8b6--201; _spacewalk-server_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWFjYjkyODI5NjE3Y2VjZmJkMGFiMzEyNDEzMWI5NjhlBjsAVEkiC2xvY2FsZQY7AEZJIgp6aC1DTgY7AFRJIgpvYXV0aAY7AFR7BkkiDHR3aXR0ZXIGOwBUewZJIhdjYWxsYmFja19jb25maXJtZWQGOwBUVA%3D%3D--4c452c1f76d48257bc6793efafbe515364650d02"
	ConvertedEnergy = 0
	EpicHelper = true

